// Packages
const Discord = require('discord.js');
const fs = require('fs');
const YAML = require('yaml');
const request = require('snekfetch');

const yaml = require('js-yaml');
// Data files
//let config = yml("./config.yml")
// functions

module.exports.errorEmbed = function(message, errorMessage) {
    const errorEmbed = new Discord.MessageEmbed()
    .setColor(`RED`)
    .setTitle(errorMessage)
    message.channel.send({embed: errorEmbed}).then(msg => {
        msg.delete(2000)
    })
}

module.exports.LogSend = async function(Message, client, config) {
    const channel = client.channels.cache.find(channel => channel.name === config.Log_Channel);
    channel.send(Message);
}

//module.exports.config = config

/*module.exports.Log = function(Message, client) {
    const channel = client.channels.cache.get(config.);
    const Embed = new Discord.MessageEmbed()
    .setColor(`BLUE`)
    .setTitle(Message)
}*/

module.exports.Embed = function(message, Message) {
    const Embed = new Discord.MessageEmbed()
    .setColor(`YELLOW`)
    .setTitle(Message)
    message.channel.send({embed: Embed}).then(msg => {
        msg.delete(2000)
    })
}

module.exports.yml = function(fileName) {
    return new Promise((resolve) => {
        try {
          resolve(YAML.parse(fs.readFileSync(fileName, 'utf-8')));
        } catch (err) {
            resolve({});
            console.log("ERROR! Config file not indented properly. Debug: " + err);
        }
    })
}


module.exports.writeYML = function(fileName, data) {
    let yamlStr = yaml.safeDump(data);
fs.writeFileSync(fileName, yamlStr, 'utf8');
}


module.exports.canModifyQueue = function(member) {
    const { channel } = member.voice;
    const botChannel = member.guild.me.voice.channel;

    if (channel !== botChannel) {
      member.send("You need to join the voice channel first!").catch(console.error);
      return false;
    }

    return true;
}

module.exports.color = function(motd, submotd){
if(!submotd) submotd = "";
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")

motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")

motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")

motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
motd = motd.replace("§0", "")
motd = motd.replace("§1", "")
motd = motd.replace("§2", "")
motd = motd.replace("§3", "")
motd = motd.replace("§4", "")
motd = motd.replace("§5", "")
motd = motd.replace("§6", "")
motd = motd.replace("§7", "")
motd = motd.replace("§8", "")
motd = motd.replace("§9", "")
motd = motd.replace("§a", "")
motd = motd.replace("§b", "")
motd = motd.replace("§c", "")
motd = motd.replace("§d", "")
motd = motd.replace("§e", "")
motd = motd.replace("§f", "")
motd = motd.replace("§k", "")
motd = motd.replace("§m", "")
motd = motd.replace("§n", "")
motd = motd.replace("§l", "")
motd = motd.replace("§o", "")
motd = motd.replace("§r", "")

submotd = submotd.replace("§0", "")
submotd = submotd.replace("§1", "")
submotd = submotd.replace("§2", "")
submotd = submotd.replace("§3", "")
submotd = submotd.replace("§4", "")
submotd = submotd.replace("§5", "")
submotd = submotd.replace("§6", "")
submotd = submotd.replace("§7", "")
submotd = submotd.replace("§8", "")
submotd = submotd.replace("§9", "")
submotd = submotd.replace("§a", "")
submotd = submotd.replace("§b", "")
submotd = submotd.replace("§c", "")
submotd = submotd.replace("§d", "")
submotd = submotd.replace("§e", "")
submotd = submotd.replace("§f", "")
submotd = submotd.replace("§k", "")
submotd = submotd.replace("§m", "")
submotd = submotd.replace("§l", "")
submotd = submotd.replace("§n", "")
submotd = submotd.replace("§o", "")
submotd = submotd.replace("§r", "")
let msg = `**${motd}**\n${submotd}`
return msg
}

module.exports.check = async (key) => {
let stat
let ActKey;
let r = await request.get('https://knzo.glitch.me/api/act?token=' + key)
if(r.body.status === 200) ActKey = r.body.msg
let r2 = await request.get('https://knzo.glitch.me/api/checkact?token=' + key + "&act=" + ActKey)
if(r2.body.status === 200) stat = true
return stat;
}